name: Release markdown files

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: 
          actions/checkout@v4
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "markdown"